nelmio_api_doc:
    documentation:
        info:
            title: Tech & Buy
            description: API de Tech & Buy
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(categories|products) # Accepts routes under /api except /api/doc
